name: Android CI
on:
 push:
  branches: [ "lab4-new" ]
 pull_request:
  branches: [ "lab4-new" ]

permissions:
 contents: read
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Check out the code
     uses: actions/checkout@v6

   - name: Set up JDK 17
     uses: actions/setup-java@v5
     with:
      distribution: temurin
      java-version: '17'

   - name: Set up Gradle
     uses: gradle/actions/setup-gradle@v5

   - name: Create google-services.json
     env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
     run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
     
   - name: Show generated file
     run: cat app/google-services.json

   - name: Make gradlew executable
     run: chmod +x gradlew

   - name: Build the app
     run: ./gradlew assembleDebug --stacktrace

   - name: Run unit tests
     run: ./gradlew testDebugUnitTest --stacktrace

   - name: Upload unit-test report
     if: always()
     uses: actions/upload-artifact@v4
     with:
      name: unit-test-report
      path: app/build/reports/tests/testDebugUnitTest
